;; hydra.init.el

; helmとカーソル操作分けた方良さそうだけどキーが余ってない...
(when (require 'hydra nil t)
  (defhydra hydra-helm (global-map "C-o")
    "helm"
    ("x" helm-M-x "helm-M-x" :exit t)
    ("y" helm-show-kill-ring "helm-show-kill-ring" :exit t)
    ("r" helm-recentf "helm-recentf" :exit t)
    ("R" helm-bookmarks "helm-bookmarks" :exit t)
    ("v" scroll-up)
    ("V" scroll-down)
    ("f" forward-word)
    ("b" backward-word)
    ("<" beginning-of-buffer)
    (">" end-of-buffer)
    ("g" keyboard-quit)
    ("C-h" backward-kill-word)
    ("SPC" set-mark-command)
    ("w" kill-ring-save)
    ("W" kill-region)
    ; (";" comment-dwin)
    (";" comment-or-uncomment-region)
    ("p" previous-line)
    ("n" next-line)
    ("N" forward-paragraph)
    ("P" backward-paragraph)
    ("h" mark-paragraph)
    ("{" shrink-window-horizontally)
    ("}" enlarge-window-horizontally)
    ("[" indent-rigidly-left)
    ("]" indent-rigidly-right)
    ("q" (message "quit") "quit" :exit t)
  ))
