;; hydra.init.el

(when (require 'hydra nil t)
  (defhydra hydra-o (global-map "C-o")
    "hydra shortcuts"
    ("x" execute-extended-command "" :exit t)
    ("y" yank-from-kill-ring "" :exit t)
    ;; depends on consult and vertico
    ("r" consult-recent-file "" :exit t)
    ("R" consult-bookmark "" :exit t)
    ("v" scroll-up)
    ("V" scroll-down)
    ("f" forward-word)
    ("b" backward-word)
    ("<" beginning-of-buffer)
    (">" end-of-buffer)
    ("g" keyboard-quit)
    ("C-h" backward-kill-word)
    ("SPC" set-mark-command)
    ("w" kill-ring-save)
    ("W" kill-region)
    ; (";" comment-dwin)
    (";" comment-or-uncomment-region)
    ("p" previous-line)
    ("n" next-line)
    ("N" forward-paragraph)
    ("P" backward-paragraph)
    ("h" mark-paragraph)
    ("{" shrink-window-horizontally)
    ("}" enlarge-window-horizontally)
    ("[" indent-rigidly-left)
    ("]" indent-rigidly-right)
    ("q" (message "quit") "quit" :exit t)
  ))
