
(when (require 'smartrep nil t)
  (global-unset-key (kbd "C-q"))
  (smartrep-define-key
   global-map "C-q" '(("n" . 'scroll-up)
                      ("p" . 'scroll-down)
                      ("f" . 'forward-word)
                      ("b" . 'backward-word)
                      ("<" . 'beginning-of-buffer)
                      (">" . 'end-of-buffer)
                      ("q" . 'keyboard-quit)
                      ("C-h" . 'backward-kill-word)
                      ("x" . 'helm-M-x)
                      ("SPC" . 'set-mark-command)
                      ("w" . 'kill-ring-save)
                      )))
